export const preta = [
    {
        src: './src/black/newSlowBlack/Acalanto.mp3',
        name: 'Acalanto',
        band: 'Black do Acordeon e Barbara Greco',
        type: 'lenta',
    },
    {
        src: './src/black/newFastBlack/Baiao.mp3',
        name: 'Baião',
        band: 'Dominguinhos, Sivuca, Oswaldinho',
        type: 'rapida',
    },
    {
        src: './src/black/newSlowBlack/Alumiou.mp3',
        name: 'Alumiou',
        band: 'Ó do forrò',
        type: 'lenta',
    },
    {
        src: './src/black/newFastBlack/Cascaxado.mp3',
        name: 'Cascaxado',
        band: 'Cascabulho',
        type: 'rapida',
    },
    {
        src: './src/black/newSlowBlack/Carinho-do-Bom.mp3',
        name: 'Carinho do Bom',
        band: 'Jaime',
        type: 'lenta',
    },
    {
        src: './src/black/newFastBlack/Forro-de-Printemps.mp3',
        name: 'Forro-de-Printemps.',
        band: 'Forró Pifado',
        type: 'rapida',
    },
    {
        src: './src/black/newSlowBlack/Caxixi.mp3',
        name: 'Caxixi',
        band: 'Mariene de Castro',
        type: 'lenta',
    },
    {
        src: './src/black/newFastBlack/Lamento-Sertanejo.mp3',
        name: 'Lamento-Sertanejo',
        band: 'Nicolas Krassik, Daniela Spielman',
        type: 'rapida',
    },
    {
        src: './src/black/newSlowBlack/EITA.mp3',
        name: 'EITA',
        band: 'Giseli de Santi',
        type: 'lenta',
    },
    {
        src: './src/black/newFastBlack/Pe-De-Calcada.mp3',
        name: 'Pe-De-Calcada',
        band: 'Mestre Ambrósio',
        type: 'rapida',
    },
    {
        src: './src/black/newSlowBlack/Naise.mp3',
        name: 'Naise',
        band: 'Nina Oliveira',
        type: 'lenta',
    },
    {
        src: './src/black/newFastBlack/Retrato-de-um-Forro.mp3',
        name: 'Retrato-de-um-Forro',
        band: 'Paulinho do Acordeon',
        type: 'rapida',
    },
    {
        src: './src/black/newSlowBlack/Onde-Esta-Voce.mp3',
        name: 'Onde Está Você',
        band: 'Mariana Aydar',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/Feira de Mangaio.mp3',
        name: 'Feira de Mangaio Instrumental',
        band:'Dominguinos',
        type: 'rapida',
    },
    {
        src: './src/black/newSlowBlack/Platonismo.mp3',
        name: 'Platonismo',
        band: 'Bicho de Pé, Janayna Pereira',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/Sebastiana.mp3',
        name: 'Sebastiana',
        band:'Rastapé',
        type: 'rapida',
    },
    {
        src: './src/black/newSlowBlack/Riso-Frouxo.mp3',
        name: 'Riso Frouxo',
        band: 'Bárbara Greco',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/Esquisitice.mp3',
        name: 'Esquisitice',
        band:'As Bastianas',
        type: 'rapida',
    },
    {
        src: './src/black/newSlowBlack/Tom-de-Alegria.mp3',
        name: 'Tom de Alegria',
        band: 'Zaíra',
        type: 'lenta',
    },
    {
        src: './src/black/slowBlack/Arpoador (2).mp3',
        name: 'Arpoador',
        band: 'Os Cincopados',
        type: 'rapida',
    },
    {
        src: './src/black/fastBlack/Aldeia.mp3',
        name: 'Aldeia',
        band: 'Estakazero',
        type: 'rapida',
    },
    {
        src: './src/black/slowBlack/Balada do Pó, Pedra e Caminho.mp3',
        name: 'Balada do Pó, Pedra e Caminho',
        band:'Forró Massapê',
    },
    {
        src: './src/black/fastBlack/Hino Malino.mp3',
        name: 'Hino Malino',
        band: 'Forró Malino',
        type: 'rapida',
    },
    {
        src: './src/black/slowBlack/Celebrai.mp3',
        name: 'Celebrai',
        band:'Relô Rolô',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/Ao meu lado é seu lugar.mp3',
        name: 'Ao meu lado é seu lugar',
        band: 'Circuladô de Fulô',
        type: 'rapida',
    },
    {
        src: './src/black/slowBlack/Porque Tem Que Ser Assim.mp3',
        name: 'Porque Tem Que Ser Assim',
        band:'Cezzinha',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/Bicho Do Mato.mp3',
        name: 'Bicho Do Mato',
        band: 'Rastapé',
        type: 'rapida',
    },
    {
        src: './src/black/slowBlack/Espere por mim morena.mp3',
        name: 'Espere por mim morena',
        band:'Caraivana',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/Cinco pra Xaxar.mp3',
        name: 'Cinco pra Xaxar',
        band:'Forró',
        type: 'rapida',
    },
    {
        src: './src/black/slowBlack/Lisbela.mp3',
        name: 'Lisbela',
        band:'Los Hermanos',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/De Frente Pro Mar.mp3',
        name: 'De Frente Pro Mar',
        band:'Estakazero',
        type: 'rapida',
    },
    {
        src: './src/black/slowBlack/Surpresa Boa.mp3',
        name: 'Surpresa Boa',
        band:'Luso Baião',
        type: 'lenta',
    },
    {
        src: './src/black/slowBlack/Noite Severina.mp3',
        name: 'Noite Severina',
        band:'Lila Queiroga',
        type: 'lenta',
    },
    {
        src: './src/black/slowBlack/Nós Dois.mp3',
        name: 'Nós Dois',
        band:'Forro Raíz',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/Filosofia.mp3',
        name: 'Filosofia',
        band:'Flávio José',
        type: 'rapida',
    },
    {
        src: './src/black/slowBlack/Ócio Criativo.mp3',
        name: 'Ócio Criativo',
        band:'Manitu',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/Nem Mesmo Eu.mp3',
        name: 'Nem Mesmo Eu',
        band:'Boi de Lata',
        type: 'rapida',
    },
    {
        src: './src/black/slowBlack/Por causa de você menina.mp3',
        name: 'Por causa de você menina',
        band: 'Buchicho',
        type: 'lenta',
    },
    {
        src: './src/black/fastBlack/Pout-Pourri.mp3',
        name: 'Pot-Pourri',
        band:'Fkávio José',
        type: 'rapida',
    },
    {
        src: './src/black/slowBlack/Saber Voar.mp3',
        name: 'Saber Voar',
        band:'Chimarruts',
        type: 'lenta',
    },
    {
        src: './src/black/slowBlack/Voz do coração.mp3',
        name: 'Voz do coração',
        band:'Ó do Forró',
        type: 'lenta',
    },
]