export const azulAv = [
    {
        src: './src/blueAv/slowAv2/Benzin.mp3',
        name: 'Benzin',
        band: 'Julliete',
        type: 'lenta',
    },
    // {
    //     src: './src/blueAv/slowAv2/Abc do Sertao.mp3',
    //     name: 'Abc do Sertao',
    //     band: 'Bicho de Pé',
    //     type: 'rapida',
    // },
    // {
    //     src: './src/blueAv/fastAv2/Castigo.mp3',
    //     name: 'Castigo',
    //     band: 'Trio Balance',
    //     type: 'lenta',
    // },
    {
        src: './src/blueAv/fastAv2/Cabeca DAgua.mp3',
        name: 'Cabeca DAgua',
        band: 'Raiz do Sana',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/De tardezinha.mp3',
        name: 'De tardezinha',
        band: 'Coisa de Zé',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Embalo Do Forro.mp3',
        name: 'Embalo Do Forro',
        band: 'Rastapé',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Dois Pra Ca.mp3',
        name: 'Dois Pra Ca',
        band: 'Nathan Carvalho',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Forro Em Arcoverde - Vai E Vem.mp3',
        name: 'Forro Em Arcoverde - Vai E Vem',
        band: 'Falamansa',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Erro eu.mp3',
        name: 'Erro eu',
        band: 'Black do arcodeon',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Forro No Claro.mp3',
        name: 'Forro No Claro',
        band: 'Rastapé',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Essa musica.mp3',
        name: 'Essa musica',
        band: 'Falamansa',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Forro pra Alice.mp3',
        name: 'Forro pra Alice',
        band: 'Filpo e a Feira',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/I Love You So.mp3',
        name: 'I Love You So',
        band: 'Forró De KA',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Forro Universitario.mp3',
        name: 'Forro Universitario',
        band: 'Rastapé',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/No colo do teu coracao.mp3',
        name: 'No colo do teu coracao',
        band: 'Coisa de Zé',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Instrumental 1D2.mp3',
        name: 'Instrumental 1D2',
        band: 'Coisa de Zé',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Pra Que Fingir.mp3',
        name: 'Pra Que Fingir',
        band: 'Dois Dobrados',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Rosalina.mp3',
        name: 'Rosalina',
        band: 'O Bando De Maria',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Segue a Vida.mp3',
        name: 'Segue a Vida',
        band: 'Falamansa',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Roseira do Norte.mp3',
        name: 'Roseira do Norte',
        band: 'Dominguinhos, Sivuca',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Miou.mp3',
        name: 'Miou',
        band: 'Falamansa',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Morena não se vá.mp3',
        name: 'Morena não se vá',
        band: 'Chama Chuva',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/A Notícia.mp3',
        name: 'A Notícia',
        band: 'Vicente Barreto',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Não Há Nada Igual ao Forró.mp3',
        name: 'Não Há Nada Igual ao Forró',
        band: 'Bicho de Pé',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Carta de um Anjo.mp3',
        name: 'Carta de um Anjo',
        band: 'Falamansa',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Acerola.mp3',
        name: 'Acerola',
        band: 'Verso e Prosa',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Mãe liberdade.mp3',
        name: 'Mãe Liberdade',
        band: 'Relô Rolô',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Baile da Tartaruga.mp3',
        name: 'Baile da Tartaruga',
        band: 'Zé Gonzaga',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Minha distância.mp3',
        name: 'Minha Distância',
        band: 'Trio Alvorada',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Canção dos Amigos.mp3',
        name: 'Canção dos Amigos',
        band: 'Kanavia',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/nossos olhos-1.mp3',
        name: 'Nossos Olhos',
        band: 'Forró Massapê',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/É Proibido Cochilar.mp3',
        name: 'É Proibido Cochilar',
        band: 'Circuladô de Fulô',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Outra Vida.mp3',
        name: 'Outra Vida',
        band: 'Armandinho',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Em contato corpo e alma.mp3',
        name: 'Em Contato Corpo e Alma',
        band: 'Trio Juremá',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Pescador (Só Parênt).mp3',
        name: 'Pescador',
        band: 'Só Parênt',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Exame.mp3',
        name: 'Exame Instrumental',
        band: 'Instrumental',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Quem me dera.mp3',
        name: 'Quem Me Dera',
        band: 'Circuladô de Fulô',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Magamalabares.mp3',
        name: 'Magamalabares',
        band: 'Circuladô de Fulô',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Recado.mp3',
        name: 'Recado',
        band: 'Cezinha',
        type: 'lenta',
    },
    {
        src: './src/blueAv/fastAv2/Mensageiro de um Rei.mp3',
        name: 'Mensageiro de um Rei',
        band: 'Fenfit',
        type: 'rapida',
    },
    {
        src: './src/black/fastBlack/Aldeia.mp3',
        name: 'Aldeia',
        band: 'Estakazero',
        type: 'rapida',
    },
    {
        src: './src/blueAv/slowAv2/Toc Toc.mp3',
        name: 'Toc Toc',
        band: 'Verso e Prosa',
    },
]