export const pre = [
    {
        src: './src/pre/Caminhada.mp3',
        name: 'Caminhada',
        band: 'Mestre Luíz Paixão',
        type: 'rapida',
    },
    {
        src: './src/pre/Forro Do Rei.mp3',
        name: 'Forro Do Rei',
        band: 'Trio Virgulino',
        type: 'rapida',
    },
    {
        src: './src/pre/Mangabeira.mp3',
        name: 'Mangabeira',
        band: 'Banda Cataia',
        type: 'rapida',
    },
    {
        src: './src/pre/O Fole Roncou.mp3',
        name: 'O Fole Roncou',
        band: 'Flávio José',
        type: 'rapida',
    },
    {
        src: './src/pre/Pao de Queijo e Forro.mp3',
        name: 'Pao de Queijo e Forro',
        band: 'Alcalyno',
        type: 'rapida',
    },
    {
        src: './src/pre/Frevoador.mp3',
        name: 'Frevoador',
        band: 'Zé Ramalho',
        type: 'arrastape',
    },
    {
        src: './src/pre/Lamparina da Historia.mp3',
        name: 'Lamparina da Historia',
        band: 'Vitor MAriá, Vovó Edite',
        type: 'arrastape',
    },
    {
        src: './src/pre/Pexera, saia e xaxado.mp3',
        name: 'Pexera, saia e xaxado',
        band: 'Trio Macaíba',
        type: 'arrastape',
    },
    {
        src: './src/pre/Pra Tirar Coco.mp3',
        name: 'Pra Tirar Coco',
        band: 'Forró Bemtivi',
        type: 'arrastape',
    },
    {
        src: './src/white/Teu Olhar.mp3',
        name: 'Teu Olhar',
        band:'Kanaviá',
        type: 'media',
    },
    {
        src: './src/white/Vou te namorar.mp3',
        name: 'Vou te namorar',
        band:'Trio Dona Zefa',
        type: 'media',
    },
    {
        src: './src/white/Xote Ecológico.mp3',
        name: 'Xote Ecológico',
        band:'Luís Gonzaga',
        type: 'media',
    },
    {
        src: './src/white/Xote na Lua.mp3',
        name: 'Xote na Lua',
        band:'Forró Lunar',
        type: 'media',
    },
    {
        src: './src/black/newSlowBlack/Acalanto.mp3',
        name: 'Acalanto',
        band: 'Black do Acordeon e Barbara Greco',
        type: 'lenta',
    },
    {
        src: './src/black/newSlowBlack/Alumiou.mp3',
        name: 'Alumiou',
        band: 'Ó do forrò',
        type: 'lenta',
    },
    {
        src: './src/black/newSlowBlack/Carinho-do-Bom.mp3',
        name: 'Carinho do Bom',
        band: 'Jaime',
        type: 'lenta',
    },
    {
        src: './src/black/newSlowBlack/Caxixi.mp3',
        name: 'Caxixi',
        band: 'Mariene de Castro',
        type: 'lenta',
    },
]